site_name: PsLogLite
site_url: https://leojackson.github.io/PsLogLite
site_description: A lightweight, procedural logging utility for use with any PowerShell script.
site_author: Leo Jackson

repo_url: https://github.com/leojackson/PsLogLite

theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - powershell
        - yaml

nav:
    - Home: index.md
    - Usage: usage.md
    - Function Reference:
        - Get-LogLevel: 'functions/Get-LogLevel.md'
        - Get-LogPath: 'functions/Get-LogPath.md'
        - Reset-LogLevel: 'functions/Reset-LogLevel.md'
        - Reset-LogPath: 'functions/Reset-LogPath.md'
        - Set-LogLevel: 'functions/Set-LogLevel.md'
        - Set-LogPath: 'functions/Set-LogPath.md'
        - Write-Debug: 'functions/Write-Debug.md'
        - Write-Error: 'functions/Write-Error.md'
        - Write-Host: 'functions/Write-Host.md'
        - Write-Information: 'functions/Write-Information.md'
        - Write-Output: 'functions/Write-Output.md'
        - Write-Verbose: 'functions/Write-Verbose.md'
        - Write-Warning: 'functions/Write-Warning.md'
    - License: license.md
    - Changelog: CHANGELOG.md