name: Build Documentation

on:
  push:
    branches: [ master ]
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'

jobs:
  mkdocs-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Prepare build environment
      run: |
        sudo apt-get update -y
        sudo apt-get install -y python-setuptools
        sudo pip3 install --upgrade pip
        sudo pip3 install mkdocs mkdocs-material mkdocs-git-revision-date-localized-plugin Markdown markdown-include MarkupSafe pymdown-extensions PyYAML
    - name: Build documentation
      run: mkdocs gh-deploy